In [20]:
""""""

''

In [21]:
import numpy as np

In [22]:
# Создадим неориентированный вектор
list_vec = [1, 2, 3] # 
arr_vec = np.array(list_vec) # это одномерный массив скобочки одинираные = неориентированный вектор
arr_vec.ndim # показывает количество измерений
arr_vec.shape # показывает количество строк и столбцов (3,) 1- param row, 2 - column

(3,)

In [23]:
# Создадим ориентированный вектор
row_vec = np.array([list_vec]) # двумерный массив  , row vector
col_vec = np.array([[1], [2], [3]])
col_vec.shape # (3, 1) три строки и один столбец

(3, 1)

In [24]:
col_vec

array([[1],
       [2],
       [3]])

In [25]:
col_vec.ndim

2

In [26]:
# broadcasting / транслирование
row_vec + col_vec 

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [28]:
row_vec + row_vec

array([[2, 4, 6]])

In [30]:
row_vec * 5

array([[ 5, 10, 15]])

In [33]:
row_vec * .5
row_vec * 1/2

array([[0.5, 1. , 1.5]])

In [35]:
dir(row_vec)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '

In [36]:
# транспонирование
row_vec.T
#array([[1],
    #    [2],
    #    [3]])

array([[1],
       [2],
       [3]])

In [40]:
row_vec * row_vec # адомаромарово произведение

array([[1, 4, 9]])